### ISSUE TITLE
WS game tick emit update 

### ISSUE THREAD

**Issue by mkoyamba** [Blubby-42-Team/ft_transcendence#42]
```
			this.logger.debug(newGameState.player_right); //TODO WS @Matthew-Dreemurr
```

https://github.com/Blubby-42-Team/ft_transcendence/blob/1a9d3a281b96b8003d417b2e9b2a0b4c4e0caf83/server/src/model/game/game.class.ts#L84

**Comment by Matthew-Dreemurr** [comment]
Done with 00ff02955e8f15144adf4563e2e0697b8cc71d3f #65
